version: '3.9'
services:
  db:
    image: postgres:15
    env_file:
      - .env.docker       # здесь только POSTGRES_* для инициализации
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build: .
    #env_file:
    #  - yoyaku/.env.local        # подхватит все DB_* для Pydantic
    environment:
      IN_DOCKER: "1"
      ENV_FILE: /app/.env.local
      GUNICORN_WORKERS: 4
    volumes:
      - .:/app:delegated
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: >
     sh -c "poetry run python manage.py migrate &&
         poetry run gunicorn yoyaku.wsgi:application --bind 0.0.0.0:8000 --workers=4 --access-logfile - --error-logfile -"




volumes:
  pg_data:
