# Generated by Django 5.2.3 on 2025-06-21 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField(unique=True, verbose_name='номер комнаты')),
                ('description', models.CharField(max_length=150, verbose_name='описание номера')),
                ('price_per_night', models.PositiveIntegerField(verbose_name='цена номера за ночь')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления номера')),
            ],
            options={
                'verbose_name': 'номер',
                'verbose_name_plural': 'номера',
                'ordering': ('room_number',),
            },
        ),
    ]
