# Generated by Django 5.2.3 on 2025-07-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='дата изменения номера'),
        ),
    ]
